version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      - test: ["CMD-SHELL", "pg_isready -U amrdc_api"]
      - interval: 5s
      - timeout: 10s
      - retries: 3
  web_service:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy 
