version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres-data:/var/lib/postgresql/data
  web_service:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db